### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by antoine-pous** [MegaGM/nodebb-plugin-mega-teamspeak#2]
Hi, can you document your plugin and provide some screenshots?

I'm really interested.

Thank you!

**Comment by MegaGM** [comment]
Sorry for the late reply. This plugin was developed on demand, exclusively for one particular website and was never meant to work with any others. Because of peculiar integration it provided to the website, like 2FA through Teamspeak and so.
It also utilizes Redis directly, without NodeBB driver, so there is no MongoDB compatibility.

I've stated in Readme that this plugin is "not production ready and just a PoC", to warn people not to try to install it.

But, actually, the plugin is working in production for many years and supports many features like realtime updating (with animations): channel info, channel tree changes, client info, client statuses, etc. It also automagically updates groups for particular Teamspeak clients when you add/remove their linked NodeBB user profiles to/from a NodeBB Group and much more.

![](https://i.imgur.com/q3GLOci.jpg)

If you're a developer and you want to develop a Teamspeak plugin yourself, you could start off by forking this repo. Or, at least, you certainly could use this repo as a reference, to see how you could implement various kinds of functionality you would need for your plugin.
